// =====================================================
// SOS ROUTES - Node.js Backend
// =====================================================
// Modules: 4 (SOS Button), 5 (Location), 11 (Intent),
//          12 (Panic Mode), 13 (Helplines), 14 (Auto Message),
//          26 (Notifications)
//
// CHANGES:
//   - /nearby endpoint now reads ?language= query param
//   - getAIEnrichedResources() receives language and builds
//     a localised Groq prompt so resource notes are generated
//     in the user's preferred language (Hindi, Tamil, etc.)
// =====================================================

const express = require('express');
const router = express.Router();
const { supabase } = require('../config/supabase');
const { authenticateUser } = require('../middleware/auth');
const { decrypt } = require('../middleware/encryption');

// ── Language name map ──────────────────────────────
const LANGUAGE_NAMES = {
  en: 'English',   hi: 'Hindi',     ta: 'Tamil',   te: 'Telugu',
  mr: 'Marathi',   bn: 'Bengali',   gu: 'Gujarati', kn: 'Kannada',
  ml: 'Malayalam', pa: 'Punjabi',
};

// =====================================================
// INTENT DETECTION + RISK SCORING (Module 11, 19)
// =====================================================

const EMERGENCY_KEYWORDS = {
  violence:     { keywords: ['attack', 'hit', 'beat', 'weapon', 'knife', 'gun', 'shoot', 'stab', 'assault', 'threatened', 'rob', 'kidnap', 'murder', 'kill'], score: 9 },
  medical:      { keywords: ['heart attack', 'unconscious', 'bleeding', 'chest pain', 'not breathing', 'seizure', 'overdose', 'allergic', 'stroke', 'fainted', 'injured'], score: 8 },
  fire:         { keywords: ['fire', 'burning', 'smoke', 'explosion', 'gas leak', 'flames'], score: 8 },
  harassment:   { keywords: ['following', 'stalking', 'harassed', 'molested', 'touched', 'unsafe', 'scared', 'help me', 'danger'], score: 7 },
  accident:     { keywords: ['accident', 'crash', 'fell', 'hit by', 'vehicle', 'collision', 'road', 'trapped'], score: 7 },
  mental_health:{ keywords: ['suicide', 'self harm', 'want to die', 'end my life', 'depressed', 'hopeless'], score: 8 },
};

function classifyEmergency(description = '', triggerType = 'manual') {
  const text = description.toLowerCase();
  let detectedType = 'other';
  let maxScore = triggerType === 'panic' ? 9 : 5;

  for (const [type, data] of Object.entries(EMERGENCY_KEYWORDS)) {
    const matched = data.keywords.some(kw => text.includes(kw));
    if (matched && data.score > maxScore) {
      maxScore = data.score;
      detectedType = type;
    }
  }

  return {
    emergency_type: detectedType,
    risk_score: Math.min(maxScore, 10),
    panic_mode: maxScore >= 9 || triggerType === 'panic',
  };
}

function buildAutoMessage(userName, emergencyType, address, riskScore) {
  const time = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
  const urgency = riskScore >= 8 ? '🚨 URGENT' : '⚠️ ALERT';
  return `${urgency} - Safety App Emergency Alert

User: ${userName}
Emergency: ${emergencyType?.toUpperCase() || 'UNSPECIFIED'}
Risk Level: ${riskScore}/10
Location: ${address || 'Location being fetched...'}
Time: ${time}

Please respond immediately. This message was auto-generated by Safety App.`;
}

// =====================================================
// ROUTE: TRIGGER SOS (Module 4, 12)
// POST /api/sos/trigger
// =====================================================
router.post('/trigger', authenticateUser, async (req, res) => {
  try {
    const {
      trigger_type = 'manual',
      description = '',
      latitude,
      longitude,
      accuracy,
      address,
      city,
      state,
    } = req.body;

    const classification = classifyEmergency(description, trigger_type);

    const { data: userData } = await supabase
      .from('users')
      .select('full_name')
      .eq('user_id', req.userId)
      .single();

    const userName = userData?.full_name || 'Unknown User';
    const autoMessage = buildAutoMessage(
      userName,
      classification.emergency_type,
      address || (latitude ? `${latitude}, ${longitude}` : null),
      classification.risk_score
    );

    const { data: incident, error: incidentError } = await supabase
      .from('sos_incidents')
      .insert([{
        user_id: req.userId,
        status: 'triggered',
        trigger_type,
        description,
        emergency_type: classification.emergency_type,
        risk_score: classification.risk_score,
        panic_mode: classification.panic_mode,
        auto_message: autoMessage,
      }])
      .select()
      .single();

    if (incidentError) throw incidentError;

    if (latitude && longitude) {
      await supabase.from('sos_locations').insert([{
        incident_id: incident.id,
        user_id: req.userId,
        latitude,
        longitude,
        accuracy: accuracy || null,
        address: address || null,
        city: city || null,
        state: state || null,
        is_initial: true,
      }]);
    }

    notifyEmergencyContacts(req.userId, incident, autoMessage, address)
      .catch(err => console.error('Contact notification error:', err));

    await supabase.from('audit_logs').insert([{
      user_id: req.userId,
      action: 'sos_triggered',
      resource_type: 'sos_incident',
      resource_id: incident.id,
      metadata: {
        trigger_type,
        emergency_type: classification.emergency_type,
        risk_score: classification.risk_score,
        panic_mode: classification.panic_mode,
      }
    }]);

    return res.status(201).json({
      success: true,
      message: 'SOS triggered successfully',
      data: {
        incident_id: incident.id,
        status: incident.status,
        risk_score: classification.risk_score,
        emergency_type: classification.emergency_type,
        panic_mode: classification.panic_mode,
        auto_message: autoMessage,
      }
    });

  } catch (error) {
    console.error('SOS trigger error:', error);
    return res.status(500).json({ success: false, error: 'Failed to trigger SOS' });
  }
});

// =====================================================
// ROUTE: UPDATE LOCATION (Module 5)
// POST /api/sos/:incidentId/location
// =====================================================
router.post('/:incidentId/location', authenticateUser, async (req, res) => {
  try {
    const { incidentId } = req.params;
    const { latitude, longitude, accuracy, altitude, speed, heading, address, city, state } = req.body;

    if (!latitude || !longitude) {
      return res.status(400).json({ success: false, error: 'latitude and longitude are required' });
    }

    const { data: incident } = await supabase
      .from('sos_incidents')
      .select('id, status')
      .eq('id', incidentId)
      .eq('user_id', req.userId)
      .single();

    if (!incident) return res.status(404).json({ success: false, error: 'Incident not found' });
    if (['resolved', 'cancelled'].includes(incident.status)) {
      return res.status(400).json({ success: false, error: 'Incident is already closed' });
    }

    if (incident.status === 'triggered') {
      await supabase.from('sos_incidents').update({ status: 'active' }).eq('id', incidentId);
    }

    const { data: loc } = await supabase.from('sos_locations').insert([{
      incident_id: incidentId,
      user_id: req.userId,
      latitude,
      longitude,
      accuracy: accuracy || null,
      altitude: altitude || null,
      speed: speed || null,
      heading: heading || null,
      address: address || null,
      city: city || null,
      state: state || null,
      is_initial: false,
    }]).select().single();

    return res.status(200).json({
      success: true,
      message: 'Location updated',
      data: { location_id: loc.id }
    });

  } catch (error) {
    console.error('Location update error:', error);
    return res.status(500).json({ success: false, error: 'Failed to update location' });
  }
});

// =====================================================
// ROUTE: RESOLVE / CANCEL SOS
// PATCH /api/sos/:incidentId/resolve
// =====================================================
router.patch('/:incidentId/resolve', authenticateUser, async (req, res) => {
  try {
    const { incidentId } = req.params;
    const { action = 'resolved', notes = '' } = req.body;

    if (!['resolved', 'cancelled', 'false_alarm'].includes(action)) {
      return res.status(400).json({ success: false, error: 'Invalid action' });
    }

    const { data: incident } = await supabase
      .from('sos_incidents')
      .select('id, status')
      .eq('id', incidentId)
      .eq('user_id', req.userId)
      .single();

    if (!incident) return res.status(404).json({ success: false, error: 'Incident not found' });

    const { data: updated } = await supabase
      .from('sos_incidents')
      .update({
        status: action,
        resolved_at: new Date().toISOString(),
        resolved_by: 'user',
        resolution_notes: notes,
      })
      .eq('id', incidentId)
      .select()
      .single();

    await supabase.from('audit_logs').insert([{
      user_id: req.userId,
      action: `sos_${action}`,
      resource_type: 'sos_incident',
      resource_id: incidentId,
      metadata: { notes }
    }]);

    return res.status(200).json({
      success: true,
      message: `SOS ${action} successfully`,
      data: { incident: updated }
    });

  } catch (error) {
    console.error('SOS resolve error:', error);
    return res.status(500).json({ success: false, error: 'Failed to resolve SOS' });
  }
});

// =====================================================
// ROUTE: ACTIVE SOS
// GET /api/sos/active
// =====================================================
router.get('/active', authenticateUser, async (req, res) => {
  try {
    const { data: incident } = await supabase
      .from('sos_incidents')
      .select('*')
      .eq('user_id', req.userId)
      .in('status', ['triggered', 'active'])
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!incident) {
      return res.status(200).json({ success: true, data: { active_incident: null } });
    }

    const { data: latestLoc } = await supabase
      .from('sos_locations')
      .select('latitude, longitude, address, created_at')
      .eq('incident_id', incident.id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    return res.status(200).json({
      success: true,
      data: {
        active_incident: { ...incident, latest_location: latestLoc || null }
      }
    });

  } catch (error) {
    console.error('Get active SOS error:', error);
    return res.status(500).json({ success: false, error: 'Failed to get active SOS' });
  }
});

// =====================================================
// ROUTE: HELP HISTORY (Module 9)
// GET /api/sos/history
// =====================================================
router.get('/history', authenticateUser, async (req, res) => {
  try {
    const { page = 1, limit = 10 } = req.query;
    const offset = (page - 1) * limit;

    const { data: history, error, count } = await supabase
      .from('help_history')
      .select('*', { count: 'exact' })
      .eq('user_id', req.userId)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (error) throw error;

    return res.status(200).json({
      success: true,
      data: {
        history,
        pagination: { page: Number(page), limit: Number(limit), total: count }
      }
    });

  } catch (error) {
    console.error('Help history error:', error);
    return res.status(500).json({ success: false, error: 'Failed to get help history' });
  }
});

// =====================================================
// ROUTE: GET HELPLINES (Module 13)
// GET /api/sos/helplines?category=police&state=Maharashtra
// =====================================================
router.get('/helplines', async (req, res) => {
  try {
    const { category, state } = req.query;

    let query = supabase
      .from('helplines')
      .select('*')
      .eq('is_active', true)
      .order('priority_order', { ascending: true });

    if (category) query = query.eq('category', category);
    if (state) query = query.or(`state.eq.${state},state.is.null`);

    const { data, error } = await query;
    if (error) throw error;

    return res.status(200).json({ success: true, data: { helplines: data } });

  } catch (error) {
    console.error('Helplines error:', error);
    return res.status(500).json({ success: false, error: 'Failed to get helplines' });
  }
});

// =====================================================
// ROUTE: NEARBY SAFETY RESOURCES (Module 15)
// GET /api/sos/nearby?lat=19.07&lng=72.87&radius=5000&type=hospital&language=hi
//
// UPDATED: Accepts ?language= and passes it to the Groq
// AI so resource names and notes are generated in the
// user's preferred language when AI enrichment is used.
// =====================================================

/**
 * Build a localised Groq system prompt for nearby resources.
 * When language is not English, the AI generates resource
 * notes (the `notes` field) in the target language.
 */
function buildNearbySystemPrompt(language) {
  const langName = LANGUAGE_NAMES[language] || 'English';
  const isEnglish = language === 'en' || !language;

  const notesInstruction = isEnglish
    ? 'Write the "notes" field in English.'
    : `IMPORTANT: Write the "notes" field in ${langName}. 
For example, if langName is Hindi, notes should be in Hindi script (Devanagari).
Resource names and addresses may remain in English/local script as they appear on maps.`;

  return `You are a safety assistant for an Indian emergency app.
Given a location (latitude, longitude), generate a list of nearby safety resources.
Return ONLY valid JSON with this exact structure:
{
  "resources": [
    {
      "name": "Resource Name",
      "resource_type": "hospital|police_station|fire_station|safe_zone|shelter",
      "address": "Full address string",
      "phone": "phone number or null",
      "latitude": 0.0,
      "longitude": 0.0,
      "distance_meters": 0,
      "is_active": true,
      "source": "ai_generated",
      "notes": "Brief helpful note about this resource"
    }
  ]
}
Rules:
- Return 5-8 realistic resources based on the area
- Use real, well-known facilities for the city/area (hospitals, police stations, fire stations)
- Estimate distances realistically based on urban density
- resource_type must be one of: hospital, police_station, fire_station, safe_zone, shelter
- phone numbers should be real Indian emergency/institutional numbers where known
- coordinates should be realistic for the area (slightly offset from user location)
- For unknown specific addresses, use area/locality name + city
${notesInstruction}`;
}

async function getAIEnrichedResources(lat, lng, radius, type, cityHint, language = 'en') {
  try {
    if (!process.env.GROQ_API_KEY) return [];

    const axios = require('axios');
    const typeInstruction = type
      ? `Focus on: ${type} resources only.`
      : 'Include a mix of hospitals, police stations, and fire stations.';

    const prompt = `User location: ${lat.toFixed(4)}, ${lng.toFixed(4)}
Search radius: ${radius}m
City/area hint: ${cityHint || 'India'}
${typeInstruction}

Generate nearby safety resources for this location. Use your knowledge of Indian cities to suggest real facilities in this area.`;

    const systemPrompt = buildNearbySystemPrompt(language);

    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user',   content: prompt },
        ],
        temperature: 0.2,
        max_tokens: 1200,
        response_format: { type: 'json_object' },
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: 15000,
      }
    );

    const raw = response.data.choices[0]?.message?.content || '{}';
    const parsed = JSON.parse(raw);
    const resources = parsed.resources || [];

    return resources
      .filter(r => !type || r.resource_type === type)
      .filter(r => r.name && r.resource_type && r.latitude && r.longitude)
      .map((r, i) => ({
        id: `ai_${Date.now()}_${i}`,
        name: r.name,
        resource_type: r.resource_type,
        address: r.address || null,
        phone: r.phone || null,
        latitude: Number(r.latitude),
        longitude: Number(r.longitude),
        distance_meters: r.distance_meters || null,
        is_active: true,
        source: 'ai_generated',
        notes: r.notes || null,
      }));
  } catch (err) {
    console.error('Groq nearby resources error:', err.message);
    return [];
  }
}

function estimateCityFromCoords(lat, lng) {
  const CITIES = [
    [18.85, 19.35, 72.75, 73.05, 'Mumbai, Maharashtra'],
    [12.85, 13.15, 77.45, 77.75, 'Bangalore, Karnataka'],
    [28.40, 28.90, 76.85, 77.40, 'Delhi'],
    [17.25, 17.55, 78.35, 78.65, 'Hyderabad, Telangana'],
    [12.95, 13.25, 80.15, 80.35, 'Chennai, Tamil Nadu'],
    [22.45, 22.65, 88.25, 88.50, 'Kolkata, West Bengal'],
    [18.45, 18.65, 73.75, 74.00, 'Pune, Maharashtra'],
    [23.00, 23.15, 72.55, 72.75, 'Ahmedabad, Gujarat'],
    [26.80, 27.00, 80.85, 81.05, 'Lucknow, Uttar Pradesh'],
    [21.10, 21.25, 79.00, 79.15, 'Nagpur, Maharashtra'],
    [15.45, 15.55, 73.80, 73.90, 'Goa'],
    [11.00, 11.15, 76.90, 77.10, 'Coimbatore, Tamil Nadu'],
    [9.90,  10.00, 76.25, 76.35, 'Kochi, Kerala'],
    [31.60, 31.70, 74.85, 74.95, 'Amritsar, Punjab'],
    [30.68, 30.78, 76.70, 76.80, 'Chandigarh'],
  ];

  for (const [minLat, maxLat, minLng, maxLng, city] of CITIES) {
    if (lat >= minLat && lat <= maxLat && lng >= minLng && lng <= maxLng) {
      return city;
    }
  }
  return 'India';
}

router.get('/nearby', async (req, res) => {
  try {
    // UPDATED: Read language from query params (default 'en')
    const { lat, lng, radius = 5000, type, language = 'en' } = req.query;

    if (!lat || !lng) {
      return res.status(400).json({ success: false, error: 'lat and lng are required' });
    }

    const latNum = Number(lat);
    const lngNum = Number(lng);
    const radiusNum = Number(radius);

    // ── 1. Query database ────────────────────────────
    const radiusDeg = radiusNum / 1000 / 111;
    const minLat = latNum - radiusDeg;
    const maxLat = latNum + radiusDeg;
    const minLng = lngNum - radiusDeg;
    const maxLng = lngNum + radiusDeg;

    let dbQuery = supabase
      .from('safety_resources')
      .select('*')
      .eq('is_active', true)
      .gte('latitude', minLat).lte('latitude', maxLat)
      .gte('longitude', minLng).lte('longitude', maxLng);

    if (type) dbQuery = dbQuery.eq('resource_type', type);

    const { data: dbData, error: dbError } = await dbQuery;
    if (dbError) throw dbError;

    const haversine = (r) => {
      const dLat = (r.latitude - latNum) * Math.PI / 180;
      const dLng = (r.longitude - lngNum) * Math.PI / 180;
      const a =
        Math.sin(dLat / 2) ** 2 +
        Math.cos(latNum * Math.PI / 180) *
        Math.cos(r.latitude * Math.PI / 180) *
        Math.sin(dLng / 2) ** 2;
      return Math.round(6371000 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
    };

    const dbResources = (dbData || []).map(r => ({
      ...r,
      source: r.source || 'manual',
      distance_meters: haversine(r),
    }));

    // ── 2. AI enrichment if DB is sparse ────────────
    // UPDATED: pass language so notes are in the right language
    const AI_THRESHOLD = 3;
    let aiResources = [];

    if (dbResources.length < AI_THRESHOLD) {
      const cityHint = estimateCityFromCoords(latNum, lngNum);
      aiResources = await getAIEnrichedResources(
        latNum, lngNum, radiusNum, type, cityHint, language
      );
    }

    // ── 3. Merge: DB first, then AI (deduplicated) ───
    const dbNames = new Set(dbResources.map(r => r.name.toLowerCase().trim()));
    const uniqueAI = aiResources.filter(r => !dbNames.has(r.name.toLowerCase().trim()));

    const merged = [...dbResources, ...uniqueAI]
      .sort((a, b) => (a.distance_meters || 99999) - (b.distance_meters || 99999));

    return res.status(200).json({
      success: true,
      data: {
        resources: merged,
        meta: {
          db_count:    dbResources.length,
          ai_count:    uniqueAI.length,
          ai_enriched: uniqueAI.length > 0,
          language,
        },
      },
    });

  } catch (error) {
    console.error('Nearby resources error:', error);
    return res.status(500).json({ success: false, error: 'Failed to get nearby resources' });
  }
});

// =====================================================
// HELPER: Notify emergency contacts (Module 26)
// =====================================================
async function notifyEmergencyContacts(userId, incident, message, address) {
  try {
    const { data: contacts } = await supabase
      .from('emergency_contacts')
      .select('*')
      .eq('user_id', userId)
      .eq('is_active', true)
      .order('priority', { ascending: true });

    if (!contacts || contacts.length === 0) return;

    const notificationRecords = [];

    for (const contact of contacts) {
      let phone = null;
      try {
        const { decrypt: dec } = require('../middleware/encryption');
        phone = dec(contact.phone_number_encrypted, contact.phone_number_iv, contact.phone_number_auth_tag);
      } catch (e) {
        console.error('Decrypt phone error:', e);
      }

      notificationRecords.push({
        incident_id:     incident.id,
        user_id:         userId,
        recipient_type:  'emergency_contact',
        recipient_id:    contact.id,
        recipient_phone: phone,
        recipient_email: contact.email || null,
        notification_type: 'sms',
        channel:         'twilio',
        message,
        status:          'pending',
      });
    }

    if (notificationRecords.length > 0) {
      await supabase.from('notifications').insert(notificationRecords);
      await supabase.from('sos_incidents').update({ contacts_notified: true }).eq('id', incident.id);
    }

  } catch (err) {
    console.error('notifyEmergencyContacts error:', err);
  }
}

module.exports = router;